### ISSUE TITLE
On-Device Learning w/ NNStreamer

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#1715]
We will probably have a lot of subtasks (backlogs) from this EPIC.
The EPIC itself might be not "TBD 2020 / Tizen 6.0 M2", but its basic features are "TBD 2020 / Tizen 6.0 M2"

Subtasks include:
- [ ] Create an example on-device learning pipeline with the given nnstreamer. (+ multi-tensor tensor_filter + modified tensor_filter::WHATSOEVER)
- [ ] Extend tensor_filter to support on-device training. Note that this should be optional; some subplugins will support on-device training and some others won't.
    - [ ] (Alternative Design) We may need yet another gst element (e.g., ```tensor_optimizer```) that updates the update-target models and let tensor_filter to update its model weights by a signal.
- [ ] Extend a few subplugins of tensor_filter to support on-device training.
- [ ] Write C-API for this.
    - [ ] Add C-API for feeding training data.
- [ ] Write C#/JAVA APIs based on the given C-API

Another EPIC-able subtask: (remove when it becomes independent.)
- [ ] Delayed / Scheduled On-Device Learning Task (may need a daemon or service or whatsoever...)

**Comment by myungjoo** [comment]
If you start writing things for/with/in nnstreamer, you may track public parts of it here.

**Comment by myungjoo** [comment]
Obsoleted by #3745
