### ISSUE TITLE
[EPIC] tensor_decoder::flatbuf, tensor_converter::flatbuf

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#1919]
Timeline: 2020.2Q (implementation) 3Q (polish, extensive testing)

TODO:
- [x] Study flatbuf, give us a seminar
- [x] Maintain flatbuf in Tizen (discuss and choose the version for Tizen-next and upgrade&integrate)
- [x] Define a standard flatbuffers representation of tensor and tensors
- [x] Write tensor_decoder::flatbuf
- [x] Write tensor_converter::flatbuf
- [x] Integrate such subplugins into Tizen
- [x] Integrate such subplugins into Ubuntu
- [x] Test with heterogeneous devices / Provide as example & sample apps
- [x] Write unit test cases

- You may create each subtask as an issue in this github repo.

**Comment by myungjoo** [comment]
Implement flatbuffer-src as tensor_converter subplugin and
implement flatbuffer-sink as tensor_decoder subplugin.
The infrastructure is ready! :)
