### ISSUE TITLE
Add NNStreamer Sample Apps

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2053]
- [ ] Basic C# Tizen Sample App @gichan-jang 
    - single C# API
    - [x] Implementation, Test, Code Merge (nnstreamer-example.git)
    - [ ] Register & publish as Tizen official application
- [ ] Basic C# Tizen Sample App w/ GUI (video output + inference result visualization) @gichan-jang
    - single C# API
    - [ ] Implementation, Test, Code Merge (nnstreamer-example.git)
    - [ ] Register & publish as Tizen official application

- [ ] Additoinal C/Native Tizen Sample App w/ GUI (video output + inference result visualization): developer-TBD
    - Use pipeline C API (no single API)
    - [ ] Implementation, Test, Code Merge (nnstreamer-example.git)
    - [ ] Register & publish as Tizen official application
- [ ] Additoinal C/Native Tizen Sample App w/ GUI (video output + inference result visualization): developer-TBD
    - Use single C API (no pipeline API)
    - [ ] Implementation, Test, Code Merge (nnstreamer-example.git)
    - [ ] Register & publish as Tizen official application
- [ ] Additioanl C/Native Tizen Sample App w/ GUI (video output + inference result visualization): developer-TBD
    - Use Tizen sensor framework. Use sensor output as an input to a neural network. (or one of the inputs for a neural network / or set of networks)
    - Use pipeline API
    - [ ] Implementation, Test, Code Merge (nnstreamer-example.git)
    - [ ] Register & publish as Tizen official application
- [ ] Additioanl C/Native Tizen Sample App w/ GUI (video output + inference result visualization): developer-TBD
    - Use edgeTPU or openVINO as accelearator. In runtime, if the accelerator is not present, use the default backend. (show the accelerator usage/avilability on the screen)
    - Use pipeline API & single API
    - [ ] Implementation, Test, Code Merge (nnstreamer-example.git)
    - [ ] Register & publish as Tizen official application

Objectives:
    - Let Tizen app developers know how to write inferences easily with ML-API/nnstreamer and how various application they may write with ML-API/nnstreamer.

If you have any questions of ambiguity to be cleared, please ask right away.

**Comment by gichan-jang** [comment]
Validation of the C# sample app will begin between April 15 and 20. I will prepare public release after the verification is complete.
