### ISSUE TITLE
[Tizen Backports] Backport to Tizen 4.0

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2221]
There is a Tizen 4.0 product, which wants to use nnstreamer. Damn.. backport it.

Build tested at https://build.tizen.org/project/show/devel:Tizen:6.0:AI:GHM_TZN4

- [x] Make nnstreamer compatible with Tizen 4.0
- [ ] Create CI task to check with Tizen 4.0
- [ ] Decide How to make backporting-patches available in tizen.org for Tizen 4.0
