### ISSUE TITLE
[~2020/10/MID] Update platform releases (yocto, macos, ubuntu)

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2732]
Both yocto and macos need recent version releases.

Yocto has higher priority (we do have users there).

### TODO / Yocto
- [x] Update nnstreamer versions @wooksong
- [x] nntrainer @anyj0527 
- Add more subplugin subpackages
  - [x] TensorFlow Lite (v1.12, v1.15.2)
  - [ ] SNPE, TF, Movidius(openvino), Edge-TPU, TensorRT, Potentially NNFW/ONE Runtime, TF-Lite 2.3, ...
- [ ] CI build check and test check for nnstreamer.git
- Enable test cases
  - [x] unittest_common
  - [x] unittest_sink
  - [x] unittest_plugins
  - [x] unittest_src_iio
  - https://github.com/nnstreamer/meta-neural-network/pull/63
    - [x] unittest_if
    - [x] unittest_join
    - [x] unittest_rate
    - [x] unittest_tizen_capi
    - [x] unittest_cppfilter
    - [x] unittest_tizen_tensorflow_lite
    - [x] SSAT

### TODO / Ubuntu
- Analize and resolve all errors there.
- Add nntrainer @anyj0527 
- Add more subplugin subpackages
- 16.04, 18.04, 20.04
- TF, TF-Lite, Caffe2, PyTorch, Movidius, Edge-TPU, TensorRT
- TF/TF-Lite 2.3

### TODO / MacOS (Get help from @wooksong )
- Update nnstreamer versions
- Add nntrainer
- Add more subplugin subpackages

**Comment by myungjoo** [comment]
Please identify which tasks are "In Progress" and which are "Done".

I think we are almost done. (except for CI-support for Yocto?)
You don't need to enable ALL features for ALL OS.


MacOS: basic features with at least one NNFW is enough.
Yocto: basic features with NNFWs required by the client's project is enough. 
Ubuntu: (18.04/20.04) most features. (16.04) basic features with at least one NNFW. We will eventually obsolete this.
Tizen: most features. 
Android: basic features with clients' requests (tf-lite, nnfw-runtime)

You don't need to overdo for Yocto/MacOS
