### ISSUE TITLE
EDGE AI

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3115]
This tracks related backlogs and epics.

- [ ] A. pub/sub stream support / maintainer: @jaeyun-jung 
    - [x] A-1. zeromq src(sub) & sink(pub) with ANY: avaiable in opensource (gst-zmq)  #3077
    - [x] A-3. mqtt src & sink with ANY: #3104 / 6.5 M1
        - PRs: #3118
    - [x] Timestamp preservation: #3196
    - [x] RTP or NTP integration: (required by #3196 to be demonstrated)
    - See if mqttsrc/sink would be enough. #3032
    - [x] High-bandwidth Support #3247 (mqtt-hybrid)
- [ ] B. query (client/server) support / maintainer: @jaeyun-jung @again4you  
    - [x] B-0. Decide the protocol, stream types. / 6.5 M1
    - [x] B-1-A. Basic 1-to-1 server with synchrnous queries. / 6.5 M1
    - [x] B-1-B. Multiple client support (n-to-1) / 6.5 M1
    - [ ] B-4. Robustness control #2703 / 6.5 M2
        - [ ] Robustness w/ hearbeats #2999
        - [x] Alternative servers
        - [ ] Alternative local resources
        - [ ] Recovery
    - [ ] B-5-B. Asynchronous queries (client-side. stretch goal. need analysis on the need) / Timeline TBD
        - This should be an optional feature enabled by a property.
- [x] C. nnstreamer-edge #2966  / 6.5 M2, 7.0 M2 @jaeyun-jung 
    - [x] C-1. nnstreamer-edge::sensor (src)
        - Design choice: use mqtt-rtos or a custom protocol paired with a new gst element "nnstreamer-edge-src". Former is better.
    - [x] C-2. nnstreamer-edge::dump (sink)
        - Design choice: use mqtt-rtos or a custom protocol paired with a new gst element "nnstreamer-edge-sink". Former is better.
    - [x] C-3. nnstreamer-edge::query 
    - [x] C-4. nnstreamer-edge for RTOS
- [x] D. FlatBuf::FlexBuffer support #3023 / maintainer: @again4you @gichan-jang  / ~May
    - [x] stream typing and flexbuffer
    - [x] tensor_decoder::flexbuffer-standard-tensors
    - [x] F-1. tensor_decoder::flexbuffer custom typing C #3086
    - [x] F-2. tensor_decoder::flexbuffer custom typing Python or Lua (need to discuss with clients) #3087
    - [x] F-1. tensor_converter::flexbuffer custom typing C #3086
    - [x] F-2. tensor_converter::flexbuffer custom typing Python or Lua (need to discuss with clients) #3087
        - F-1 and F-2 are not restricted to FlexBuf. They should be applicable to any type.
        - However, providing APIs or "syntactic sugar" for FlexBuf is desirable.
- [ ] Flexible dimensions / maintainer: @jaeyun-jung  / May~June + 6.5 M2
    - [x] E. FlexTensor
        - [x] FlexTensor CAP and Header design.
        - [x] FlexTensor for tensor-filter
        - [x] FlexTensor converter/decoder (be careful w/ dynamic GSTCAP). We may need to use sparse-tensor w/ limited size.
        - [x] FlexTensor for tensor-*
    - [ ] Tensor Composite #3017
    - [x] SparseTensor @anyj0527 
        - [x] Datatype definition
        - [x] SparseTensor converter/decoder (2021/2Q)
        - [x] SparseTensor direct handling w/ a few tensor-fitler subplugins (2021/3Q)
        - [x] Expansion of SparseTensor handling with other tensor-* (2022)
    - [x] General compression (gzip/zlib/or/...): available in opensource #2936
        - [x] Integration into Tizen / @anyj0527 
    - [x] Prototyping support
        - [x] F-3. tensor-filter::LUA #3095 / @anyj0527 
            - PRs: #3101
- [x] ML-API Support
    - [x] C-API / 6.5 M2 #3119
    - [x] C#-API
    - [ ] Java-API
    - [ ] C++-API
- [ ] Edge-AI Standard Protocol
    - [ ] Document Protocols: pub/sub
    - [ ] Document Protocols: pub/sub hybrid
    - [ ] Document Protocols: query
    - [ ] Document Protocols: nnstreamer-edge
    - [ ] Implement protocols: nnstreamer (should've been done automatically with above sub tasks)
    - [ ] Implement protocols: mediapipe #3353 
    - [ ] Implement protocols: deepstream #3359
    - note: nnstreamer-edge can be seen as "Implement protocols: RTOS devices"

**Comment by myungjoo** [comment]
This is being obsolete. Need to update soon!

**Comment by myungjoo** [comment]
Remaining Tasks: C#, Web APIs!

**Comment by myungjoo** [comment]
Closing this 2021 umbrella. The pipeline-side items it tracked (pub/sub sources and sinks, MQTT, nnstreamer-edge, query elements, timestamp handling) have all shipped, and the only remaining note from 2023-10-16 is C# and Web APIs, which belong to the nnstreamer/api repository rather than here. Anything still wanted on the edge side should be filed as a concrete issue against the component it touches.
