### ISSUE TITLE
[ML-API] C-API for Edge-AI Capabilities

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3119]
TBD

**During May/June 2021**,  let's discuss pub/sub first.
- [x] Step 1. Determine if Edge-AI ML-API is required for pub/sub elements
==> Determined that it is **NOT** required.
~~Step 2. Define API prototypes (headers), Start ACR : **Deadline: early-July 2021**~~
~~Step 3. Define test cases (public TCT & internal UTC)~~
~~Step 4. Implement & Test: Deadline: Sep 2021~~
~~Step 5. Release & Complete ACR~~

After query is designed, let's discuss query-related APIs (June/July 2021?)
- [x] Step 1. Determine if Edge-AI ML-API is required for query related elements
~~Step 2. Define API prototypes (headers), Start ACR : **Deadline: late-July 2021**~~
~~Step 3. Define test cases (public TCT & internal UTC)~~
~~Step 4. Implement & Test: Deadline: Sep 2021~~
~~Step 5. Release & Complete ACR~~

If no additional API (ACR) is required for these capabilities, you can complete by
- [ ] Add public TCT testing pub/sub, query
- [ ] Add internal UTC testing such
- [ ] Update API documents & Tizen user guide (how to use such)
- [ ] (Make sure) all related components are properly integrated into Tizen 6.5 M2 (and its images)

CC: @again4you : ML C-API design reviewer.

**Comment by myungjoo** [comment]
Conclusion: the current API already supports this. We just need additional documentation and sample apps for Edge-AI.

**Comment by myungjoo** [comment]
Released.
