### ISSUE TITLE
[Parser/WYSIWYG] GstPipe-Mediapipe(pbtxt) Converter

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3354]
After #2123 and  #3270, we need the followings

- [ ] Documentation (user guide) of #3270 usage
- [ ] pbtxt-->gstpipe conversion (reverse of #3270)
- [ ] gstpipe --> pbtxt --> gstpipe compatibility checks
