### ISSUE TITLE
[Parser/WYSIWYG] GstPipe-Mediapipe(pbtxt) conversion in real-time w/ GUI

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#3355]
After #3354 we can further advance.

- [ ] Integrate gstpipe-->pbtxt & pbtxt-->gstpipe converter w/ mediapipe web tools
- [ ] Draw pipelines w/ mediapipe tools, export gstpipe output, run the output w/ nnstreamer+gstreamer: **(A)**
- [ ] Edit pipeline **(A)** (or other "working" gstpipe) w/ mediepipe tools, export gstpipe output, run the output w/ nnstreamer+gstreamer.
- [ ] Except for "running gst pipe", everything could be done in mediapipe Web GUI tool or its "web extension".
