### ISSUE TITLE
[EPIC/NR1] Dynamic Pipeline Modification

### ISSUE THREAD

**Issue by ohsewon** [nnstreamer/nnstreamer#420]
This is a long-term item requiring modifications in many elements.

Need to start in 1902A with trivial elements and test cases.

- [x] tensor_repo_src/sink #1057 #1058 #906
- [ ] Trivial Elements: tensor_{converter, mux, demux, merge, split, sink}
- [ ] Basic test cases.
- [ ] tensor_filter
    - NNFW & Model changes with proper deallocations & error handling
- [ ] tensor_decoder
    - Subplugin deallocation & error handling
- [ ] tensor_aggregator
- [ ] OTHERS?

We need example application (as a test case as well) that modifies tensor_* related pipelines in run-time.

We need to ensure that it's possible with our plugins.

**Comment by ohsewon** [comment]
<a href="https://github.sec.samsung.net/git-bot-sec"><img src="https://github.sec.samsung.net/avatars/u/63289?" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [git-bot-sec](https://github.sec.samsung.net/git-bot-sec)**
_Thursday Jul 26, 2018 at 11:50 GMT_

----

:octocat: **cibot**: Thank you for posting issue #354. The person in charge will reply soon.

**Comment by myungjoo** [comment]
This became TBD from Sprint1811B because Project:AD related issues have higher priority.

**Comment by myungjoo** [comment]
No one is requesting this and we see no evidence of this being not supported at this moment.
Resurrect when needed.
