### ISSUE TITLE
[EPIC] tensor_decoder::protobuf / tensor_converter::protobuf

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#849]
Timeline: 2020.2Q (implementation) 3Q (polish, extensive testing)

TODO:
- [x] Study protobuf, give us a seminar  @anyj0527 
- [x] Maintain protobuf in Tizen (discuss and choose the version for Tizen-next and upgrade&integrate)
- [x] Define a standard protobuf representation of tensor and tensors
- [x] Write tensor_decoder::protobuf
- [x] Write tensor_converter::protobuf
- [x] Integrate such subplugins into Tizen
- [x] Integrate such subplugins into Ubuntu
- [ ] Test with heterogeneous devices / Provide as example/sample apps
- [x] Write unit test cases

- You may create each subtask as an issue in this github repo.

For future applications with multi-computer devices,
we may need more than ROS; we may need to send protobuf messages via ROS or general UDP.

We need to study and discuss whether we really need to support protobuf or not.
If we need to support protobuf, it means that we need to make tensor-protobuf and protobuf-tensor converters.
